# Generated by Django 5.2 on 2025-04-26 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('source_currency', 'target_currency', 'date', 'time')},
        ),
    ]
