# Generated by Django 5.2 on 2025-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mmk_inflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mmk_outflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mmk_per_thb_buy_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mmk_per_thb_sell_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='thb_inflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='thb_outflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='thb_per_100k_mmk_buy_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='thb_per_100k_mmk_sell_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
