# Generated by Django 5.2 on 2025-04-26 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_mmk_inflow_transaction_mmk_outflow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='googlesheetconfig',
            options={'verbose_name_plural': 'Google Sheet Configurations'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_id',
            new_name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='googlesheetconfig',
            name='sheet_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mmk_inflow',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mmk_outflow',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mmk_per_thb_buy_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mmk_per_thb_sell_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='thb_inflow',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='thb_outflow',
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_location',
            field=models.CharField(blank=True, help_text='Location where the currency is exchanged', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='buy_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Rate at which we buy the source currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='sell_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Rate at which we sell the source currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='googlesheetconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='googlesheetconfig',
            name='exchange_rates_range',
            field=models.CharField(default='Rates!A2:F', help_text="Range for exchange rates (e.g., 'Rates!A2:F')", max_length=100),
        ),
        migrations.AddField(
            model_name='googlesheetconfig',
            name='transactions_range',
            field=models.CharField(default='Transactions!A2:M', help_text="Range for transactions (e.g., 'Transactions!A2:K')", max_length=100),
        ),
        migrations.AddField(
            model_name='googlesheetconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, help_text='Related transaction (buy transaction for a sell, or vice versa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transactions', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='Currency code (e.g., USD, THB)', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='Currency name (e.g., US Dollar, Thai Baht)', max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(help_text='Currency symbol (e.g., $, ฿)', max_length=5),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(help_text='Date when this rate is effective'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time when this rate is effective'),
        ),
        migrations.AlterField(
            model_name='googlesheetconfig',
            name='credentials_json',
            field=models.TextField(help_text='Google API credentials JSON'),
        ),
        migrations.AlterField(
            model_name='googlesheetconfig',
            name='sheet_id',
            field=models.CharField(help_text='Google Sheet ID from the sheet URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_source', to='api.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_target', to='api.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='thb_per_100k_mmk_buy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='thb_per_100k_mmk_sell_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
