# Generated by Django 5.2 on 2025-04-26 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeLeftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Original exchange rate', max_digits=10)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
            ],
        ),
    ]
