# Generated by Django 5.2 on 2025-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exchangeleftover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheetconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='googlesheetconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googlesheetconfig',
            name='exchange_rates_range',
        ),
        migrations.RemoveField(
            model_name='googlesheetconfig',
            name='transactions_range',
        ),
        migrations.RemoveField(
            model_name='googlesheetconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='googlesheetconfig',
            name='sheet_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlesheetconfig',
            name='credentials_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlesheetconfig',
            name='sheet_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy (Customer MMK → THB)'), ('SELL', 'Sell (Customer THB → MMK)')], max_length=4),
        ),
    ]
