# Generated by Django 5.0.2 on 2025-05-08 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.CharField(max_length=200)),
                ('thb_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mmk_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('hundred_k_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
