# Generated by Django 5.2 on 2025-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_hundred_k_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('OTHER', 'Other Profit')], default='BUY', max_length=5),
        ),
    ]
