# Generated by Django 5.0.2 on 2025-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mmk_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
