# Generated by Django 5.0.2 on 2025-06-06 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['currency', 'name'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='dailybalance',
            options={'ordering': ['-date', 'bank_account__currency', 'bank_account__name'], 'verbose_name': 'Daily Balance', 'verbose_name_plural': 'Daily Balances'},
        ),
        migrations.AlterModelOptions(
            name='dailyexchangerate',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Exchange Rate', 'verbose_name_plural': 'Daily Exchange Rates'},
        ),
        migrations.AlterModelOptions(
            name='dailyprofit',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Profit', 'verbose_name_plural': 'Daily Profits'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['name'], 'verbose_name': 'Expense Type', 'verbose_name_plural': 'Expense Types'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_time'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('THB', 'Thai Baht'), ('MMK', 'Myanmar Kyat')], help_text='Currency of the bank account', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the account', null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the account is currently active'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(help_text='Name of the bank account', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Account balance on this date', max_digits=15),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='bank_account',
            field=models.ForeignKey(help_text='Bank account this balance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='transactions.bankaccount'),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='date',
            field=models.DateField(help_text='Date of this balance record'),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this balance entry', null=True),
        ),
        migrations.AlterField(
            model_name='dailyexchangerate',
            name='date',
            field=models.DateField(help_text='Date for this exchange rate', unique=True),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='buy_sell_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit from buy/sell transactions in THB', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='date',
            field=models.DateField(help_text='Date of this profit record', unique=True),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='other_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Profit from 'OTHER' type transactions in THB", max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total profit (buy_sell_profit + other_profit) in THB', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Expense amount in THB', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(help_text='Date when this expense occurred'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(help_text='Short description of the expense', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(help_text='Type of expense', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='transactions.expensetype'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or details', null=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this expense type', null=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this expense type is currently active'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(help_text='Name of the expense type', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(db_index=True, help_text='Customer name or identifier', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the transaction occurred'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hundred_k_rate',
            field=models.DecimalField(decimal_places=2, help_text='THB amount per 100,000 MMK', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mmk_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Myanmar Kyat', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit amount in THB', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Exchange rate (MMK per THB)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or comments', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='thb_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Thai Baht', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy (Customer MMK → THB)'), ('SELL', 'Sell (Customer THB → MMK)'), ('OTHER', 'Other Profit')], db_index=True, default='BUY', help_text='Type of transaction (BUY: Customer gives MMK, gets THB; SELL: Customer gives THB, gets MMK)', max_length=5),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date_time', 'transaction_type'], name='transaction_date_ti_9a3604_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer'], name='transaction_custome_d6a353_idx'),
        ),
    ]
