# Generated by Django 5.0.2 on 2025-06-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_bankaccount_options_alter_dailybalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='matched_with',
            field=models.IntegerField(blank=True, help_text='ID of the matching transaction (for profit calculation)', null=True),
        ),
    ]
