# Generated by Django 5.0.1 on 2025-06-19 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_transaction_matched_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['currency', 'name']},
        ),
        migrations.AlterModelOptions(
            name='dailybalance',
            options={'ordering': ['-date', 'bank_account__currency', 'bank_account__name']},
        ),
        migrations.AlterModelOptions(
            name='dailyexchangerate',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dailyprofit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_time']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_date_ti_9a3604_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_custome_d6a353_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='matched_with',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('THB', 'Thai Baht'), ('MMK', 'Myanmar Kyat')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='transactions.bankaccount'),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexchangerate',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='buy_sell_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='other_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyprofit',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='transactions.expensetype'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hundred_k_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mmk_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='thb_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('OTHER', 'Other Profit')], db_index=True, default='BUY', max_length=5),
        ),
    ]
